### ISSUE TITLE
Cache result

### ISSUE THREAD

**Issue by seymores** [seymores/gc_nlp#2]
CacheX is probably a good choice to cache the result for 10 seconds by default.

**Comment by whitfin** [comment]
@seymores I'd be glad to PR this in for you 😄! I'll fire one over as soon as I get a moment to work on it. I'll also include #1 seeing as they seem particularly coupled. 

Couple of things before I start:
- I noticed you said "by default" - would you like the ability to override adding to `config.exs`?
- What specifically needs to be cached? At a glance it appears to be just `make_request/3`?
